import {
  Check,
  BookOpen,
  CircleAlert,
  CircleHelp,
  Copy,
  Database,
  Download,
  ExternalLink,
  ListFilter,
  FolderOpen,
  FolderPlus,
  FlipHorizontal,
  FlipVertical,
  Image as ImageIcon,
  Info,
  Keyboard,
  Layers3,
  LayoutGrid,
  Pencil,
  Palette,
  Pin,
  PinOff,
  Plus,
  RotateCcw,
  RotateCw,
  Star,
  ChevronLeft,
  ChevronRight,
  RefreshCw,
  Search,
  Settings,
  Sparkles,
  Tags,
  Trash2,
  Upload,
  X,
  ZoomIn,
  ZoomOut,
} from 'lucide-react';
import { Icon as LobeIcon } from '@lobehub/ui';

const ICONS = {
  book: BookOpen,
  check: Check,
  close: X,
  copy: Copy,
  database: Database,
  download: Download,
  edit: Pencil,
  externalLink: ExternalLink,
  filter: ListFilter,
  folder: FolderOpen,
  folderPlus: FolderPlus,
  flipHorizontal: FlipHorizontal,
  flipVertical: FlipVertical,
  image: ImageIcon,
  info: Info,
  keyboard: Keyboard,
  library: LayoutGrid,
  layers: Layers3,
  plus: Plus,
  previous: ChevronLeft,
  next: ChevronRight,
  palette: Palette,
  pin: Pin,
  pinOff: PinOff,
  refresh: RefreshCw,
  search: Search,
  settings: Settings,
  spark: Sparkles,
  star: Star,
  tags: Tags,
  restore: RotateCcw,
  rotateLeft: RotateCcw,
  rotateRight: RotateCw,
  trash: Trash2,
  upload: Upload,
  warning: CircleAlert,
  help: CircleHelp,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
};

export function getIconComponent(name) {
  return ICONS[name] || CircleHelp;
}

export default function Icon({ name, size = 17, strokeWidth = 1.8, ...props }) {
  const Component = getIconComponent(name);
  return <LobeIcon aria-hidden="true" focusable="false" icon={Component} size={size} strokeWidth={strokeWidth} {...props}/>;
}
